### ISSUE TITLE
Create smoother arc resizing

### ISSUE THREAD

**Issue by light-layer** [light-layer/light-layer.github.io#1]
Arc resizing is buggy in safari on desktop (see video)

Uploading Screen Recording 2021-07-08 at 11.08.27 AM.mov…

Jobs:
- change viewport resizing thresholds?

**Comment by sgogos1** [comment]
Not seeing a video here?

**Comment by sgogos1** [comment]
Will work on ensuring that the arc is relatively static in shape and size no matter the dimensions of the screen.

**Comment by sgogos1** [comment]
Arc resizing is now much much smoother. As far as I've observed it locks to the bottom of the page and the peak is always above the comment. 

Keeping this open until @micah-olivas @light-layer confirms this as well.

**Comment by sgogos1** [comment]
Closing this issue. Seems the arc is sizing properly across the board.
