### ISSUE TITLE
Fix website differences on mobile

### ISSUE THREAD

**Issue by sgogos1** [light-layer/light-layer.github.io#12]
Website renders entirely differently depending on the phone and the browser being used on that phone.
e.g.:
- Instagram's browser - Worked really well, scroll-locked, everything rendered properly
- Chrome - Website scrolls, bottom portion (due to address bar disappearing) is white (not grey) and arc overlaps with logo.
- Free Adblock Browser - Spacing is really large between each part of the content to the point where logo is fully above the arc.

Need to figure out how to remove variables that are causing differences.

**Comment by sgogos1** [comment]
Added dynamic resizing of the main element in index.js. Hoping that removes the issue with the address bar changing the screen port size.

Merging into main to be able to test if it worked.

**Comment by light-layer** [comment]
Noticed some element overlap and arc problems with Instagram browser on iPhone 12.
![IMG_2307E691B5F0-1](https://user-images.githubusercontent.com/87216193/125335565-8c1b3d80-e301-11eb-98f7-54650581ba8f.jpeg)

**Comment by sgogos1** [comment]
Can you confirm how it looks on all iOS browsers you have accessible?

Looks good on android with:
- instagram
- twitter
- chrome
- free adblock browser
- duck duck go
- firefox

**Comment by sgogos1** [comment]
Closing this ticket as it seems it has been solved (at least for now).
