### ISSUE TITLE
Change position of elements on mobile

### ISSUE THREAD

**Issue by light-layer** [light-layer/light-layer.github.io#2]
On mobile, elements appear too low on screen (see screenshot). Center elements within the text arc and move upward slightly.

Jobs:
- Change arc coordinates
- move all elements upward on mobile

**Comment by sgogos1** [comment]
Not seeing a screenshot here?

**Comment by light-layer** [comment]
![image](https://user-images.githubusercontent.com/87216193/125248689-33b85180-e2a9-11eb-9860-ff3a9faeee97.png)

**Comment by light-layer** [comment]
These comments are covered in sgogos1's mobile devices issue. Closing.
