### ISSUE TITLE
Add social links and hover over animations

### ISSUE THREAD

**Issue by light-layer** [light-layer/light-layer.github.io#3]
Add links to instagram and mixcloud below calendar

Jobs:

Add offset strings below calendar
Use source code pro font for links
Configure hover-over animation with logo colors (mixcloud = #5001fe, instagram = #f45d3a)

**Comment by sgogos1** [comment]
Opened a new branch from dev (add-social-links) in order to add the links underneath the calendar with hover color change.

**Comment by sgogos1** [comment]
Added the social links in dev accidentally as opposed to on the add-social-links branch. But features were successfully added and are working.
