### ISSUE TITLE
Create announcement feature

### ISSUE THREAD

**Issue by light-layer** [light-layer/light-layer.github.io#4]
As title, description elements, and calendar transition downward, text bubble png transitions in along with the announcement.

Todos:
- Title/description/calendar transitions (should padding for each element change with vertical transition?)
- Fade in `graphics/speech-bubble.png`
- Ingest announcement from `json/announcment.json`

**Comment by sgogos1** [comment]
Added an announcement bubble and text that fade in after the arc has done one complete round.
