### ISSUE TITLE
Add site development/hiatus announcement

### ISSUE THREAD

**Issue by light-layer** [light-layer/light-layer.github.io#44]
I'll be taking a break from broadcasting and site updates until I'm finished with my qualifying exam at the end of Nov. In the meantime, I'd like to add a few "in development" features:

- The announcement bubble displays a quote from a database of quotes if no announcement is scheduled to run on a given day. These can take the form "LL reminds you: ..."
- Text on the arch shows "Light Layer is on a brief hiatus. Broadcasts will return on 11/26" or something like that

**Comment by sgogos1** [comment]
Hiatus arch text has been added.

Need a database of quotes from you @micah-olivas to get the other fix.

**Comment by light-layer** [comment]
Database of quotes (`quotes.csv`) now stored in csv directory.
