### ISSUE TITLE
Github pages claims CNAME domain is improperly configured

### ISSUE THREAD

**Issue by light-layer** [light-layer/light-layer.github.io#6]
`light-layer>settings>pages` throws an error about DNS and domain being misconfigured.

**Comment by sgogos1** [comment]
Website is now live via https://light-layer.github.io and https://lightlayerradio.com

Fixed it by:
- Specifying CNAME with lightlayerradio.com in this repository.
- In the domain provider:
     - Specifying the A records with Github's server IP addresses
     - Specifying CNAME with light-layer.github.io

Issue is considered fixed.
